# Generated by Django 2.0.7 on 2018-09-02 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('chatu', models.ImageField(upload_to='chatu/%Y/%m', verbose_name='文章插图')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('change_time', models.DateField(auto_now=True, verbose_name='最近修改时间')),
                ('article_tage', models.CharField(max_length=50, verbose_name='文章标签')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner/%Y/%m', verbose_name='轮播图')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
                ('change_time', models.DateField(auto_now=True, verbose_name='最近修改时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='评论者名称')),
                ('email', models.EmailField(max_length=254, verbose_name='评论者邮箱')),
                ('customer_url', models.SlugField(verbose_name='评论者网站')),
                ('comment', models.TextField(verbose_name='评论')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('comment_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='文章')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='作者')),
                ('picture', models.ImageField(upload_to='writer/%Y/%m', verbose_name='作者头像')),
                ('user_tag', models.CharField(max_length=100, verbose_name='作者标签')),
                ('user_view', models.TextField(verbose_name='作者语句')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='首次加入时间')),
                ('change_time', models.DateField(auto_now=True, verbose_name='最近修改时间')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Writer', verbose_name='作者'),
        ),
    ]
