# Generated by Django 2.0.7 on 2018-09-03 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='writer',
            name='for_self',
            field=models.CharField(default='', max_length=200, verbose_name='自我介绍'),
        ),
    ]
