# Generated by Django 2.0.7 on 2018-09-03 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180903_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=30, verbose_name='作者标签')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户标签',
                'verbose_name_plural': '用户标签',
            },
        ),
        migrations.CreateModel(
            name='User_view',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_view', models.TextField(verbose_name='作者语句')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户语句',
                'verbose_name_plural': '用户语句',
            },
        ),
        migrations.RemoveField(
            model_name='writer',
            name='user_tag',
        ),
        migrations.RemoveField(
            model_name='writer',
            name='user_view',
        ),
        migrations.AddField(
            model_name='user_view',
            name='user_view_writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Writer', verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='user_tag',
            name='user_tag_writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Writer', verbose_name='作者'),
        ),
    ]
