# Generated by Django 2.0.7 on 2018-09-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180903_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='jiexuan',
            field=models.CharField(default='', max_length=200, verbose_name='文章节选'),
        ),
    ]
